name: Publish

on:
  workflow_run:
    workflows: ["Checks"]
    branches: [master]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Install dependencies
        run: |
          sudo sed -i 's/azure.archive.ubuntu.com/archive.ubuntu.com/' /etc/apt/sources.list
          sudo apt-get -qq update
          sudo apt install -qq -y libudev-dev
      - uses: actions/checkout@v4
      - name: Publish new release
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
